name: family_poc
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+2

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0

  shared_preferences: ^2.0.18
  background_locator_2: ^2.0.5
  path_provider: ^2.0.13
  intl: ^0.18.0
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #
